### ISSUE TITLE
Stack can't find apecs-physics-gloss via git

### ISSUE THREAD

**Issue by RobertGlorioso** [jonascarpay/apecs-physics#4]
Is there a way to get Stack to find the apec-physics-gloss package? Stack complains it doesn't have the dependency for it when I build.

It finds and builds apecs-physics just fine.

Here is my .yaml:
```
resolver: lts-9.11
packages: [.]
extra-deps:
  - apecs-0.3.0.2
  - gloss-juicy-0.2.2
  - sdl2-mixer-1.1.0
  - git: https://github.com/jonascarpay/apecs-physics.git
    commit: 4bc304544c1c3136f3b9557c0bbb12724a1a8213

flags: {}
extra-package-dbs: []
```

Maybe give apecs-physics-gloss it's own repo?
